### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by ali-m-github** [arcaneiceman/Kraken#13]
Hello!
I am unable to register, getting "Network Error"

**Comment by arcaneiceman** [comment]
Sorry about this. This is because Ive taken the server offline. In about a week or two, I intend to open the server side code as well as try to upload as many password lists ive collected as possible to allow people to use this system openly

**Comment by arcaneiceman** [comment]
Sorry for the delay on this. The system has been partially rewritten to be released on docker now. All server and client code is posted :)

**Comment by Mehliug-git** [comment]
Hello, I have the same problem...
