### ISSUE TITLE
 The length of HTTPS certificate exceeds the limit when accessing the URL 

### ISSUE THREAD

**Issue by hamigua9527** [arcaneiceman/Kraken#23]
The length of HTTPS certificate exceeds the limit when accessing the URL

**Comment by hamigua9527** [comment]
https://192.168.244.147:8443/login  Login prompt netword error

**Comment by arcaneiceman** [comment]
Thanks for letting me know. Ill check it out and report back to see what is happening!

**Comment by arcaneiceman** [comment]
Sounds like you were able to log in. May i close this?
