### ISSUE TITLE
 Hello, I have entered the cracking page. It seems that this tool can only crack WiFi packets, right 

### ISSUE THREAD

**Issue by hamigua9527** [arcaneiceman/Kraken#24]
Hello, I have entered the cracking page. It seems that this tool can only crack WiFi packets, right

**Comment by arcaneiceman** [comment]
Hi! 

Currently, yes, but Kraken can be extended to support any kind of brute force. Only cracking WiFi is a soft lock. You can enable MD5 and NTLM (Windows SAM Algo) with minor code modification (although the desktop client does not support NTLM yet. You'd have to modify the client-hashcat interface). The browser client supports it and it one needs minor tweaks to the server. In fact, thanks for bringing this up.

Ive made the server modification and will push it to docker image soon

**Comment by arcaneiceman** [comment]
The server can now accept NTLM requests, but I have not enabled NTLM by default until I can add that to the desktop client. Will release that change soon! For now, closing this ticket :)
