### ISSUE TITLE
Running headless?

### ISSUE THREAD

**Issue by darrenmartyn** [arcaneiceman/Kraken#25]
Stupid question, but is there a way to run the client (the "cracking" end) headlessly, for example on a number of ec2/etc systems without window managers? Is this a planned feature? Just put in the server info in a config and let it run?

**Comment by arcaneiceman** [comment]
That's an interesting use case! I can certainly look into it. Thanks for bringing it up. I could possibly modify KrakenWorker.js and run it on a node server.

 I have some optimization tasks I would like to address but after that I could certainly add it to the roadmap. The server also hosts swagger doc in case someone wants to write this in a different language. If there is enough traction, I can reprioritize it :)
