### ISSUE TITLE
Correct order of execution

### ISSUE THREAD

**Issue by robbpaulsen** [arcaneiceman/kraken#27]
Hi, sorry to bother, to be honest its not very clear to me what or in what order to acces what. On the side of building the platform its very intuitive, you did an amazing job, back to the issue I already have my cap files, dump files, dictionaires ready to upload but where I tried on the address given on the console but flags me an error when trying to browse my files, went to the other address and well couldnt find how to upload the files.

I know its a cracking tool, but does it has more features? i just might not be understanding the README english its not my first language, anyways thanks for your time and your tool, nice day!

**Comment by arcaneiceman** [comment]
Hi! 

Sorry, this is my first public project and I'm trying to learn as fast as I can so there is no bother :). 

Currently the way it works is, that when the minio container deploys, it creates a persistent volume. To add your wordlists to minio, here are the steps:
1. [UI way] Access your minio console at http://localhost:9001/. Should land you here:

![image](https://user-images.githubusercontent.com/4005494/164892721-a2d58af4-b569-4646-a24f-06aa851a1665.png)
2. Log in with u:admin p:password (default; can be changed). A 'kraken' bucket should be present like so:

![image](https://user-images.githubusercontent.com/4005494/164892791-5be36a85-bb72-40ae-a52f-0a2d2802cb0b.png)
3. Hit 'Browse' to see what files are available and add the wordlists you with 'Upload'

![image](https://user-images.githubusercontent.com/4005494/164893024-b55b4a17-1e83-46c3-8363-ffaae5257f77.png)
4. Either wait up to 5 minutes for the server to pick it up or restart the server. You'll know the server has picked up the list when via log. Note: Large lists take a while to index.

![image](https://user-images.githubusercontent.com/4005494/164893050-41ecf42c-c40c-4bde-81eb-dac5eb4b5c74.png)
5. The wordlist should show up when creating the request

![image](https://user-images.githubusercontent.com/4005494/164893097-0b990b97-cae5-4ccd-9474-73d9a9ae31ba.png)

I have some improvements that I have in mind but I primarily wrote Kraken to be an out of the box solution to distributed brute-force password cracking. Currently it supports WPA/WPA2 but I'll be adding NTLM support for the desktop client soon and enabling it by default. Please let me know if this helped.

**Comment by robbpaulsen** [comment]
Thanks a lot, and sorry for the late response, as soon as I test it agains, I´ll get back to you, have a nice day
