### ISSUE TITLE
lots of little bugs, and a few feature requests

### ISSUE THREAD

**Issue by xal3xhx** [arcaneiceman/kraken#3]
running on the windows client v1.0.2

-------------
bugs bugs and more bugs

- when a working is running, switch to help tab (or other tabs) worker goes away, https://i.imgur.com/P661676.png but still shows in "your workers", goes offline after a few minutes

- email verification/password reset is very VERY delayed..

- window can not be resized, leaving a scroll bar that is useless and just plain annoying

- appears to be a delay from opening a pcap file to when it shows on the window

- appears to be some sort of error in verification the ssid of a pcap file, only one of my pcap files seams to work properly. (could be a bug in the way i captured it, haven't looked into it yet)

- question mark on the crunch settings does nothing

- large delay of values between the 3 windows "YOUR ACTIVE REQUESTS" "YOUR WORKERS" and "WORKER"
-------------
Feature requests

- ability to select your own word list file?

- support for txt files containing hash

- cpu worker support

- ability to change name of workers

- a single link (to an all in one client download) or a command to easily start a worker on another pc

- max 12 characters for a name? why is that?

- worker utilization/info 

- a way to view hashcat output for easy error hunting
-------------
finial thoughts

i love this and all the work that you have already put into it, i would be happy to give you a hand and learn along the way.

keep up the great work with this project, it has a huge amount of potential!

**Comment by xal3xhx** [comment]
ps. im the one that sent you that email about the verification/password reset delay

**Comment by arcaneiceman** [comment]
Thank you so much for your detailed feedback. And I'm really sorry for the number of bugs you experienced! Im on it! I'll start pumping out fixes asap. 
 There are a bunch of things I can fix immediately so I'll start knocking them off one by one.

**Comment by xal3xhx** [comment]
dont be sorry, beta is beta! take your time im in no rush. you have my discord so feel free to add me, id love to help you and learn something! if i find anything else ill be sure to update this.

**Comment by xal3xhx** [comment]
quick update, found a few more bugs for you to take a look at..
on the latest build,
- web ui does not load well on mobile. https://i.imgur.com/ZH9X4wj.png
- stopping a worker from "WORKER" does not actually stop the worker
- stopping a worker form "YOUR WORKERS" will stop the current worker, but the client will just start a new one. (both web and client)
- multiple browser workers can be started on the same machine (does not cause any problems but dont think it should be possible as it pins cpu at 100% and does no work)
- closing browser tabs while worker is running/working takes quite a while before it is reflected in the "YOUR WORKERS" panel

--------
feature request
- a way to turn off the "request complete" emails


as always keep up the good work with this!

**Comment by arcaneiceman** [comment]
Hey @xal3xhx 

v1.0.4 Updated a bunch of the bugs you pointed out:

> - when a working is running, switch to help tab (or other tabs) worker goes away, https://i.imgur.com/P661676.png but still shows in "your workers", goes offline after a few minutes

Now a confirmation prompt is shown when an action will lead to the worker stopping
> - window can not be resized, leaving a scroll bar that is useless and just plain annoying

Window is now resizable (but has a min size)

> - question mark on the crunch settings does nothing

Links are now fixed

> - large delay of values between the 3 windows "YOUR ACTIVE REQUESTS" "YOUR WORKERS" and "WORKER"

There should be little to no delay now for these thanks to an event bus library

For some of the other bugs pointed out :
> - web ui does not load well on mobile.

Oh yeah, the web app isnt responsive. Its on my list of things to address after the technical bugs

 > - multiple browser workers can be started on the same machine (does not cause any problems but dont think it should be possible as it pins cpu at 100% and does no work)

I would like to address this at some point through browser local storage but there are a few extra edge cases I need to work out.

For the rest I'll keep releasing updates and adding features requested!

**Comment by arcaneiceman** [comment]
> stopping a worker from "WORKER" does not actually stop the worker
> stopping a worker form "YOUR WORKERS" will stop the current worker, but the client will just start a new one. (both web and client)

This should be fixed.

> multiple browser workers can be started on the same machine (does not cause any problems but dont think it should be possible as it pins cpu at 100% and does no work)

A note has been added with an entry in FAQ section about multiple browser workers.

I will close this issue and open new issues for the remaining ones
