### ISSUE TITLE
Impossible to register client

### ISSUE THREAD

**Issue by Mehliug-git** [arcaneiceman/Kraken#42]
Hello !

I have installed the server with docker and all OK, but I can't register with the client because I have a "Network Error", How I solve the issue please ? 

thx 4 all

**Comment by arcaneiceman** [comment]
Thanks for bringing this up. I will look into it + enhance the start screen with proper verification of connection to the server.

**Comment by Mehliug-git** [comment]
Thanks for your works

**Comment by arcaneiceman** [comment]
While I start the rewrite/rework, let me investigate what might be going wrong here. What is host name of the machine where you have run the docker-compose ? Ideally the server should be available at https://[your host]:8443/api.

If you have a screen shot of the error, please post it here! Thanks!

**Comment by Mehliug-git** [comment]
Thanks for yout time, I don't have any screenshot but the name of the computer is like : XX-POSTE01

But I will try on my PC kali I think it should be better

**Comment by arcaneiceman** [comment]
In that case, once you have ensured that all the containers are running (using docker-compose up), verify that the server is running. Easiest way to tell is to hit : http://XX-POSTE01:5000/swagger. You should be able to see the swagger documentation page. If this is up, the server API url should be https://XX-POSTE01:8443/api

**Comment by Mehliug-git** [comment]
Ok I will try it 

Thx for your help
