### ISSUE TITLE
Cannot register/login on a local instance

### ISSUE THREAD

**Issue by XaaT** [arcaneiceman/kraken#6]
Hi',

May be i misunderstood the purpose of this application.
I cloned it, build it and launched it. I saw nothing in ./config to be changed
Once i launch the instance i got onto the classic index page.
Trying to login like "just testing this button" and :
```
×
TypeError: Cannot read property 'replace' of undefined
Login.render
src/containers/Login/Login.js:81
  78 | <SocialLoginWrapper
  79 |     autoCleanUri
  80 |     provider='github'
> 81 |     gatekeeper={process.env.REACT_APP_API_URL.replace("/api", "") + '/gatekeeper/github'}
     | ^  82 |     appId='c3748a4951a1807e6eef'
  83 |     redirect='https://kraken.work/login'
  84 |     onLoginSuccess={(authObject) => this.socialAuthenticate('github', authObject)}
View compiled

Login.render
http://localhost:3001/static/js/main.chunk.js:10376:87
  10373 | })), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_components_SocialLoginWrapper_SocialLoginWrapper__WEBPACK_IMPORTED_MODULE_2__["default"], {
  10374 |   autoCleanUri: true,
  10375 |   provider: "github",
> 10376 |   gatekeeper: Object({"NODE_ENV":"development","PUBLIC_URL":""}).REACT_APP_API_URL.replace("/api", "") + '/gatekeeper/github',
        |                                                                                   ^  10377 |   appId: "c3748a4951a1807e6eef",
  10378 |   redirect: "https://kraken.work/login",
  10379 |   onLoginSuccess: authObject => this.socialAuthenticate('github', authObject),
```

Forwarding port through SSH to get http access on localhost:3001. VM can access web but strict firewall. Just access, no return and opening some ports on internet. Why ? This is a local instance, no need to.

Is this software mandatory linked to kraken.work ?
This is not a local solution allowing me to use some servers through lan access to launch hashcat ?

Thanks for the work !
---
Feature request : Add interface to add workers (like IP, ssh port, keys or local keys, etc) to remotely

**Comment by arcaneiceman** [comment]
Hi @Xaat! 

Kraken was designed to centralize a bunch of tasks (password list maintenance and job distribution) using the kraken.work server. Ive kept the server source temporarily closed source, because my hope is to first popularize the platform itself and eventually adding community-based features where people can crack other's lists for bounties although I havent quite worked it out yet. If you would like, drop me an [email](mailto:waliusmani@gmail.com) and I can give you access if you want to install it locally.
